Update redox_syscall, ignore test failures on unsupported arches

diff --git a/src/redox-syscall/debian/rules b/src/redox-syscall/debian/rules
--- a/src/redox-syscall/debian/rules
+++ b/src/redox-syscall/debian/rules
@@ -1,7 +1,15 @@
 #!/usr/bin/make -f
+include /usr/share/rustc/architecture.mk
 %:
 	dh $@ --buildsystem cargo
 
 # Upstream at this version requires nightly features :(
+# They also only work on specific architectures, so ignore test failures elsewhere.
 override_dh_auto_test:
-	RUSTC_BOOTSTRAP=1 dh_auto_test
+	export RUSTC_BOOTSTRAP=1; \
+	case $(DEB_HOST_RUST_TYPE) in \
+	arm-*|x86-*|x86_64-*) \
+	  dh_auto_test;; \
+	*) \
+	  dh_auto_test || true;; \
+	esac
